-- ============================================================================= 
-- 🚀 PRISMIFY DATABASE SETUP
-- =============================================================================
-- Copy and paste this entire file into Supabase SQL Editor and click "Run"
-- This will create all tables, indexes, and security policies
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- =============================================================================
-- USERS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    company_name VARCHAR(255),
    subscription_tier VARCHAR(50) DEFAULT 'starter' CHECK (subscription_tier IN ('starter', 'professional', 'enterprise')),
    subscription_status VARCHAR(50) DEFAULT 'active' CHECK (subscription_status IN ('active', 'cancelled', 'past_due', 'trialing')),
    stripe_customer_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login_at TIMESTAMP WITH TIME ZONE,
    email_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE users IS 'User accounts and subscription information';

-- =============================================================================
-- API KEYS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS api_keys (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_hash VARCHAR(255) NOT NULL,
    key_prefix VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    last_used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE api_keys IS 'API keys for programmatic access';

-- =============================================================================
-- SEO PROJECTS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS seo_projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    website_url VARCHAR(500),
    target_keywords TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE seo_projects IS 'SEO projects managed by users';

-- =============================================================================
-- SEO ANALYSES TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS seo_analyses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id UUID REFERENCES seo_projects(id) ON DELETE CASCADE,
    content_url VARCHAR(500),
    content_text TEXT,
    analysis_type VARCHAR(50) NOT NULL,
    results JSONB NOT NULL,
    seo_score INTEGER CHECK (seo_score >= 0 AND seo_score <= 100),
    keyword_density JSONB,
    readability_score DECIMAL(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ai_provider VARCHAR(50)
);

COMMENT ON TABLE seo_analyses IS 'SEO analysis results generated by AI';

-- =============================================================================
-- META TAGS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS meta_tags (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id UUID REFERENCES seo_projects(id) ON DELETE CASCADE,
    title VARCHAR(255),
    description TEXT,
    keywords TEXT[],
    og_title VARCHAR(255),
    og_description TEXT,
    og_image VARCHAR(500),
    twitter_card VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ai_provider VARCHAR(50)
);

COMMENT ON TABLE meta_tags IS 'AI-generated SEO meta tags';

-- =============================================================================
-- API USAGE TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS api_usage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint VARCHAR(255) NOT NULL,
    method VARCHAR(10) NOT NULL,
    status_code INTEGER,
    response_time_ms INTEGER,
    ai_provider VARCHAR(50),
    tokens_used INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date DATE DEFAULT CURRENT_DATE
);

COMMENT ON TABLE api_usage IS 'API usage tracking for billing and analytics';

-- =============================================================================
-- SUBSCRIPTION HISTORY TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS subscription_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_tier VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    stripe_subscription_id VARCHAR(255),
    amount_cents INTEGER,
    currency VARCHAR(3) DEFAULT 'USD'
);

COMMENT ON TABLE subscription_history IS 'Historical record of subscription changes';

-- =============================================================================
-- PERFORMANCE INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_stripe ON users(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_subscription ON users(subscription_tier, subscription_status);

CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_prefix ON api_keys(key_prefix);
CREATE INDEX IF NOT EXISTS idx_api_keys_active ON api_keys(is_active) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_seo_projects_user ON seo_projects(user_id);
CREATE INDEX IF NOT EXISTS idx_seo_projects_active ON seo_projects(user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_seo_analyses_user ON seo_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_seo_analyses_project ON seo_analyses(project_id);
CREATE INDEX IF NOT EXISTS idx_seo_analyses_created ON seo_analyses(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_meta_tags_user ON meta_tags(user_id);
CREATE INDEX IF NOT EXISTS idx_meta_tags_project ON meta_tags(project_id);

CREATE INDEX IF NOT EXISTS idx_api_usage_user_date ON api_usage(user_id, date);
CREATE INDEX IF NOT EXISTS idx_api_usage_created ON api_usage(created_at DESC);

-- =============================================================================
-- AUTOMATIC TIMESTAMP UPDATES
-- =============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_users_timestamp ON users;
CREATE TRIGGER update_users_timestamp
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_projects_timestamp ON seo_projects;
CREATE TRIGGER update_projects_timestamp
    BEFORE UPDATE ON seo_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- UTILITY FUNCTIONS
-- =============================================================================

-- Get daily API usage count for a user
CREATE OR REPLACE FUNCTION get_daily_usage_count(p_user_id UUID, p_date DATE DEFAULT CURRENT_DATE)
RETURNS INTEGER AS $$
BEGIN
    RETURN (
        SELECT COUNT(*)
        FROM api_usage
        WHERE user_id = p_user_id
        AND date = p_date
    );
END;
$$ LANGUAGE plpgsql STABLE;

-- Get user's subscription tier limits
CREATE OR REPLACE FUNCTION get_user_tier_limit(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE
    v_tier VARCHAR(50);
BEGIN
    SELECT subscription_tier INTO v_tier
    FROM users
    WHERE id = p_user_id;
    
    RETURN CASE v_tier
        WHEN 'starter' THEN 100
        WHEN 'professional' THEN 1000
        WHEN 'enterprise' THEN 999999
        ELSE 0
    END;
END;
$$ LANGUAGE plpgsql STABLE;

-- Check if user has exceeded their daily limit
CREATE OR REPLACE FUNCTION check_rate_limit(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
    v_usage INTEGER;
    v_limit INTEGER;
BEGIN
    v_usage := get_daily_usage_count(p_user_id);
    v_limit := get_user_tier_limit(p_user_id);
    
    RETURN v_usage < v_limit;
END;
$$ LANGUAGE plpgsql STABLE;

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE meta_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_history ENABLE ROW LEVEL SECURITY;

-- Users table policies
DROP POLICY IF EXISTS "Users can view own profile" ON users;
CREATE POLICY "Users can view own profile" ON users
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON users;
CREATE POLICY "Users can update own profile" ON users
    FOR UPDATE USING (auth.uid() = id);

-- API keys policies
DROP POLICY IF EXISTS "Users can manage own API keys" ON api_keys;
CREATE POLICY "Users can manage own API keys" ON api_keys
    FOR ALL USING (auth.uid() = user_id);

-- SEO projects policies  
DROP POLICY IF EXISTS "Users can manage own projects" ON seo_projects;
CREATE POLICY "Users can manage own projects" ON seo_projects
    FOR ALL USING (auth.uid() = user_id);

-- SEO analyses policies
DROP POLICY IF EXISTS "Users can manage own analyses" ON seo_analyses;
CREATE POLICY "Users can manage own analyses" ON seo_analyses
    FOR ALL USING (auth.uid() = user_id);

-- Meta tags policies
DROP POLICY IF EXISTS "Users can manage own meta tags" ON meta_tags;
CREATE POLICY "Users can manage own meta tags" ON meta_tags
    FOR ALL USING (auth.uid() = user_id);

-- API usage policies
DROP POLICY IF EXISTS "Users can view own usage" ON api_usage;
CREATE POLICY "Users can view own usage" ON api_usage
    FOR SELECT USING (auth.uid() = user_id);

-- Subscription history policies
DROP POLICY IF EXISTS "Users can view own subscription history" ON subscription_history;
CREATE POLICY "Users can view own subscription history" ON subscription_history
    FOR SELECT USING (auth.uid() = user_id);

-- =============================================================================
-- ✅ SETUP COMPLETE!
-- =============================================================================
-- Run "SELECT * FROM users LIMIT 1;" to verify tables were created
